timezone: US/Eastern

author:
  name: Seemant Kulleen
  email: seemantk@gmail.com
  url: http://seemantk.com
  gihub: seemantk

# Title of the window in the user's browser's
title: "Judicial Selection: An Interactive Map"
description: "Judicial selection processes for all 50 states and DC. Covers all three state court levels: State Supreme Courts, Intermediate Appellate Courts and Trial Courts."
organization:
  name: Brennan Center for Justice
  url: http://brennancenter.org
  logo: /img/bcj_logo.png
  logo_caption: Go to the main Brennan Center for Justice website.
  favicon: http://www.brennancenter.org/sites/all/themes/bcj-zen/favicon.ico

# Extra Software needed (that github-pages supports)
gems:
  - jekyll-coffeescript

# Google Analytics:
#   - Note: please paste the entire token, starting with "UA-",
analytics:
  google:
    tracking_id: '' # eg 'UA-***'

# The _introduction directory contains the intro columns
collections:
  introduction:
    output: false

# Users don't need these files
exclude: ["js/vendor/*.js", "css/vendor/*.css",  "Makefile", "$package.json", "CNAME", "README.md", "colors.css", "style.css", "Gemfile", "Gemfile.lock", "*.log", "package.json", "bower.json", "bower_components", "node_modules" ]
